### ISSUE TITLE
Dead video links

### ISSUE THREAD

**Issue by remram44** [uwescience/reproducible#13]
It appears that the links to `panopto.uw.edu` that worked previously have become unaccessible to the public. I reached out to UW IT and was told:

> The video you are trying to access is no longer available for the public. We recommend contacting the creator of the video or the website administrator for further information. 

Example such video: http://uwescience.github.io/reproducible/presentations.html#19-may-2015---reproducibility-seminar

Is there a way those could be made available in a different way? Barring that, would you mind sharing the recording of this specific session with us? We never made a copy for ourselves :sweat_smile:

cc ViDA-NYU/reprozip#324

**Comment by arokem** [comment]
Adding the panopto help email to this thread (because, why not?)

We would like to make a Panopto video available to the public again, or at
least be able to download it (see below). Please advise.

**Comment by arokem** [comment]
The videos are here (thanks to @rjleveque's fast response!): 

https://drive.google.com/drive/folders/1CRUray-CNmOtHiW9jljDI6BHjGuz4Ofe?usp=sharing

Please download and let me know when you have the files, so that I can remove them.

**Comment by remram44** [comment]
Awesome, got them thanks!
